// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: link_visits.sql

package sqlc

import (
	"context"
)

const countLinkVisits = `-- name: CountLinkVisits :one
SELECT COUNT(*)::bigint AS count FROM link_visits
`

func (q *Queries) CountLinkVisits(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLinkVisits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVisit = `-- name: CreateVisit :execrows
INSERT INTO link_visits (link_id, ip, referer, user_agent, status)
VALUES ($1, $2, $3, $4, $5)
`

type CreateVisitParams struct {
	LinkID    int64  `json:"link_id"`
	Ip        string `json:"ip"`
	Referer   string `json:"referer"`
	UserAgent string `json:"user_agent"`
	Status    int32  `json:"status"`
}

func (q *Queries) CreateVisit(ctx context.Context, arg CreateVisitParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createVisit,
		arg.LinkID,
		arg.Ip,
		arg.Referer,
		arg.UserAgent,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLinkVisits = `-- name: GetLinkVisits :many
SELECT id, link_id, ip, referer, user_agent, status, created_at
FROM link_visits
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetLinkVisitsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetLinkVisits(ctx context.Context, arg GetLinkVisitsParams) ([]LinkVisit, error) {
	rows, err := q.db.QueryContext(ctx, getLinkVisits, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LinkVisit{}
	for rows.Next() {
		var i LinkVisit
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.Ip,
			&i.Referer,
			&i.UserAgent,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
