name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://test_user:test_pass@localhost:5432/test_db?sslmode=disable
      BASE_SHORT_URL: https://short.io/r

    steps:
    - uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version: '1.26'

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.13

    - name: Run migrations
      run: make migrate-up

    - name: Run Tests
      run: make test-race

    - name: Run Build
      run: make build
